### ISSUE TITLE
Could not resolve: org.clyze:clue-common:3.25.3

### ISSUE THREAD

**Issue by 75ACOL** [BytecodeDL/soot-fact-generator#4]
获取不到这个包，什么样的gradle配置才可以获取

**Comment by waderwu** [comment]
你先从release里面下载打包好的，等我下周再看看为啥会有这个问题

**Comment by waderwu** [comment]
先pull一下，然后尝试执行`./gradlew build` 看能不能build，我本地可以这样build

**Comment by SuperXiaoxiong** [comment]
这两个源坏掉了，访问过去 503
```
maven {    name "soot-snapshot"    url "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot"}
maven {    name "soot-release"    url "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release"}
```

删掉使用
```
    maven {
        url "http://centauri.di.uoa.gr:8081/artifactory/plast-public"
        allowInsecureProtocol true // for Gradle 7 compatibility
    }
    maven { url 'https://clyze.jfrog.io/artifactory/default-maven-local' }
```

**Comment by waderwu** [comment]
> maven {    name "soot-snapshot"    url "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-snapshot"}
maven {    name "soot-release"    url "https://soot-build.cs.uni-paderborn.de/nexus/repository/soot-release"}

这两个即使503了也没啥影响，因为会先从mavenCentral()加载，org.soot-oss:soot:4.2.1 这个版本在mavenCentral是有的

**Comment by waderwu** [comment]
org.clyze 这几个存在jfrog上的依赖挂了，我通过添加submodule，本地编译这些依赖，解决了这个问题
